version: 2
updates:
  - package-ecosystem: "npm"  # Ecosistema de dependencias (Node.js)
    directory: "/"           # Carpeta raíz del proyecto
    schedule:
      interval: "weekly"     # Frecuencia de las actualizaciones
